// <auto-generated />
using System;
using FantasyFootball.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FantasyFootball.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FantasyFootballDbContext))]
    [Migration("20260329224152_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("FantasyFootball.Core.Entities.ExpertEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("CustomWeight")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(1.0);

                    b.Property<string>("DraftRankings")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DraftRankingsLastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RosRankings")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RosRankingsLastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WeeklyRankings")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("WeeklyRankingsLastUpdated")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Experts");
                });

            modelBuilder.Entity("FantasyFootball.Core.Entities.PlayerEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DepthChartOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FantasyPositions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FantasyProsId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InjuryStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SleeperId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Team")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("YearsExp")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FantasyProsId")
                        .IsUnique();

                    b.HasIndex("SleeperId")
                        .IsUnique();

                    b.ToTable("Players");
                });

            modelBuilder.Entity("FantasyFootball.Core.Entities.ExpertEntity", b =>
                {
                    b.OwnsOne("FantasyFootball.Core.Entities.AccuracyEntity", "DraftAccuracy", b1 =>
                        {
                            b1.Property<int>("ExpertEntityId")
                                .HasColumnType("INTEGER");

                            b1.Property<int?>("Dst")
                                .HasColumnType("INTEGER")
                                .HasColumnName("DraftAccuracy_Dst");

                            b1.Property<int?>("Idp")
                                .HasColumnType("INTEGER")
                                .HasColumnName("DraftAccuracy_Idp");

                            b1.Property<int?>("K")
                                .HasColumnType("INTEGER")
                                .HasColumnName("DraftAccuracy_K");

                            b1.Property<int>("OverallRank")
                                .HasColumnType("INTEGER")
                                .HasColumnName("DraftAccuracy_OverallRank");

                            b1.Property<int?>("Qb")
                                .HasColumnType("INTEGER")
                                .HasColumnName("DraftAccuracy_Qb");

                            b1.Property<int?>("Rb")
                                .HasColumnType("INTEGER")
                                .HasColumnName("DraftAccuracy_Rb");

                            b1.Property<int?>("Te")
                                .HasColumnType("INTEGER")
                                .HasColumnName("DraftAccuracy_Te");

                            b1.Property<int?>("Wr")
                                .HasColumnType("INTEGER")
                                .HasColumnName("DraftAccuracy_Wr");

                            b1.HasKey("ExpertEntityId");

                            b1.ToTable("Experts");

                            b1.WithOwner()
                                .HasForeignKey("ExpertEntityId");
                        });

                    b.OwnsOne("FantasyFootball.Core.Entities.AccuracyEntity", "WeeklyAccuracy", b1 =>
                        {
                            b1.Property<int>("ExpertEntityId")
                                .HasColumnType("INTEGER");

                            b1.Property<int?>("Dst")
                                .HasColumnType("INTEGER")
                                .HasColumnName("WeeklyAccuracy_Dst");

                            b1.Property<int?>("Idp")
                                .HasColumnType("INTEGER")
                                .HasColumnName("WeeklyAccuracy_Idp");

                            b1.Property<int?>("K")
                                .HasColumnType("INTEGER")
                                .HasColumnName("WeeklyAccuracy_K");

                            b1.Property<int>("OverallRank")
                                .HasColumnType("INTEGER")
                                .HasColumnName("WeeklyAccuracy_OverallRank");

                            b1.Property<int?>("Qb")
                                .HasColumnType("INTEGER")
                                .HasColumnName("WeeklyAccuracy_Qb");

                            b1.Property<int?>("Rb")
                                .HasColumnType("INTEGER")
                                .HasColumnName("WeeklyAccuracy_Rb");

                            b1.Property<int?>("Te")
                                .HasColumnType("INTEGER")
                                .HasColumnName("WeeklyAccuracy_Te");

                            b1.Property<int?>("Wr")
                                .HasColumnType("INTEGER")
                                .HasColumnName("WeeklyAccuracy_Wr");

                            b1.HasKey("ExpertEntityId");

                            b1.ToTable("Experts");

                            b1.WithOwner()
                                .HasForeignKey("ExpertEntityId");
                        });

                    b.Navigation("DraftAccuracy");

                    b.Navigation("WeeklyAccuracy");
                });
#pragma warning restore 612, 618
        }
    }
}
